autoscale:
  image: rancher/autoscale:v0.0.1
  environment:
    SERVICE: ${SERVICE}
    CPU_THRESHOLD_PCT: ${CPU_THRESHOLD_PCT}
    CPU_THRESHOLD_PERIOD: ${CPU_THRESHOLD_PERIOD}
    CONTAINER_WARMUP: ${CONTAINER_WARMUP}
  labels:
    io.rancher.container.start_once: 'true'
