autoscale:
  image: rancher/autoscale:v0.0.1
  command: |
    service ${SERVICE}
      --cpu ${CPU_THRESHOLD_PCT}
      --period ${CPU_THRESHOLD_PERIOD}
      --warmup ${CONTAINER_WARMUP}
  labels:
    io.rancher.container.start_once: 'true'
