autoscale:
  image: rancher/autoscale:v0.0.1
  command: |
    service ${SERVICE}
      --cpu ${CPU_THRESHOLD_PCT}
      --mem ${MEM_THRESHOLD_PCT}
      --period ${THRESHOLD_PERIOD}
      --warmup ${CONTAINER_WARMUP}
  labels:
    io.rancher.container.start_once: 'true'
  links:
  - cadvisor

# proxy cadvisor traffic hack
# connect on host ip, port 9244
cadvisor:
  image: rancher/haproxy-cadvisor:v0.0.1
  labels:
    io.rancher.scheduler.global: 'true'
  net: host