autoscale:
  image: rancher/autoscale:v0.0.1
  command: |
    service ${SERVICE}
      --cpu ${CPU_THRESHOLD_PCT}
      --mem ${MEM_THRESHOLD_PCT}
      --period ${THRESHOLD_PERIOD}
      --warmup ${CONTAINER_WARMUP}
  labels:
    io.rancher.container.start_once: 'true'
cadvisor:
  image: rancher/haproxy-cadvisor:v0.0.1
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.dns: true
   net: host