triplea:
  image: llparse/triplea:v1
  environment:
  - NAME=${NAME}
  - EMAIL=${EMAIL}
  - PORT=${PORT}
  - MAX_HEAP=256m
  ports:
  - "${PORT}:${PORT}"
  labels:
    io.rancher.scheduler.affinity:container_label_ne: triplea=${NAME}
    triplea: ${NAME}
