triplea:
  image: llparse/triplea:v1
  environment:
  - NAME=${NAME}
  - SUPPORT_EMAIL=${SUPPORT_EMAIL}
  ports:
  - "0:3304"
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: triplea=server
    triplea: server
