zookeeper:
  image: llparse/zookeeper:latest
  environment:
    ZK_ENSEMBLE_SIZE: ${ZK_ENSEMBLE_SIZE}
    ZK_TICK_TIME: ${ZK_TICK_TIME}
    ZK_INIT_LIMIT: ${ZK_INIT_LIMIT}
    ZK_SYNC_LIMIT: ${ZK_SYNC_LIMIT}
    ZK_MAX_CLIENT_CXNS: ${ZK_MAX_CLIENT_CXNS}
  labels:
    io.rancher.sidekicks: data
  volumes_from:
  - data
data:
  image: llparse/zookeeper:latest
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  volumes:
  - /data
  - /log
