.catalog:
  name: Kubernetes
  version: v1.2.4-rancher8
  description: Rancher Kubernetes service
  minimum_rancher_version: v1.1.0

etcd:
    scale_policy:
        min: 1
        max: 3
        increment: 1
    metadata:
        scale_policy:
            min: 1
#    health_check:
#        request_line: GET /health HTTP/1.0
#        port: 2379
#        interval: 3000
#        response_timeout: 2000
#        unhealthy_threshold: 3
#        healthy_threshold: 2

# Sidekick health checks don't work?

kubernetes:
    metadata:
        sans:
        - "IP:10.43.0.1"
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 80
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2
    retain_ip: true

#scheduler:
#    health_check:
#        request_line: GET /healthz HTTP/1.0
#        port: 10251
#        interval: 5000
#        response_timeout: 3000
#        unhealthy_threshold: 3
#        healthy_threshold: 2

#controller-manager:
#    health_check:
#        request_line: GET /healthz HTTP/1.0
#        port: 10252
#        interval: 5000
#        response_timeout: 3000
#        unhealthy_threshold: 3
#        healthy_threshold: 2

kubernetes-lb:
    load_balancer_config:
        haproxy_config: {"defaults": "timeout tunnel 86400000"}
    scale_policy:
        min: 1
        max: 2
        increment: 1
    health_check:
        port: 42
        interval: 5000
        response_timeout: 3000
        healthy_threshold: 2
        unhealthy_threshold: 3

rancher-kubernetes-agent:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10240
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2

kubectld:
    health_check:
        port: 8091
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2


rancher-ingress-controller:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10241
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2

