.catalog:
  version: 3.7
  minimum_rancher_version: v1.0.0
  questions:
  - variable: NUM_NODES
    description: Desired number of Cassandra nodes.
    label: Number of Nodes
    required: true
    default: 1
    type: int
  - variable: CLUSTER_NAME
    description: Desired name for the cluster (if lauching over existing data, names must match previous deployment)
    label: Cluster Name
    required: true
    default: Rancher Cluster
    type: string
  - variable: HEAP_NEWSIZE
    description: The initial heap size of the JVM
    label: Initial Heap Size
    required: true
    default: 800M
    type: string
  - variable: MAX_HEAP_SIZE
    description: The maximum heap size of the JVM
    label: Max Heap Size
    required: true
    default: 4G
    type: string
  - variable: VOLUME_MOUNT
    description: "Absolute path for a host bind mount or <[a-zA-Z0-9][a-zA-Z0-9_.-]*> for a named volume"
    label: Persistence Location
    required: true
    default: cassandra
    type: string
cassandra:
  scale: ${NUM_NODES}
  retain_ip: true
  health_check:
    port: 9042
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 1
    unhealthy_threshold: 2