master:
  image: llparse/mesos-master:${VERSION}
  environment:
    MESOS_CLUSTER: ${MESOS_CLUSTER}
    MESOS_QUORUM: ${MESOS_QUORUM}
    ZK_SERVICE: ${ZK_SERVICE}
    ZK_CHROOT: ${ZK_CHROOT}
    ZK_SESSION_TIMEOUT: ${ZK_SESSION_TIMEOUT}
  ports:
  - "${MASTER_PORT}:5050"
  labels:
    mesos: master
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:container_label_soft_ne: mesos=slave
slave:
  image: llparse/mesos-slave:${VERSION}
  environment:
    ZK_SERVICE: ${ZK_SERVICE}
    ZK_CHROOT: ${ZK_CHROOT}
  labels:
    mesos: slave
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:container_label_soft_ne: mesos=master
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
#marathon:
#  image: mesoscloud/marathon:${VERSION}
