master:
  image: llparse/mesos-master:${VERSION}
  environment:
    MESOS_QUORUM: ${MESOS_QUORUM}
    ZK_SERVICE: ${ZK_SERVICE}
    ZK_CHROOT: ${ZK_CHROOT}
  ports:
  - "5050:5050"
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    mesos: master
slave:
  image: llparse/mesos-slave:${VERSION}
  environment:
    ZK_SERVICE: ${ZK_SERVICE}
    ZK_CHROOT: ${ZK_CHROOT}
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    mesos: slave
#  net: host
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
#marathon:
#  image: mesoscloud/marathon:${VERSION}
