#!/bin/bash -e

M2_DIR="$PWD/.m2"

mkdir -p "$M2_DIR"
docker run --rm -it -v "$M2_DIR":/root/.m2 -v "$PWD":/usr/src/app -w /usr/src/app maven:3.3.9-jdk-8 mvn clean install
mv target/rancher-cassandra-*.jar target/rancher-cassandra.jar
