etcd:
  image: llparse/etcd:v2.3.7-2
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: etcd-hc,data
  environment:
    ETCD_DATA_DIR: /data
    RANCHER_DEBUG: '${DEBUG}'
  volumes_from:
  - data

etcd-hc:
  image: llparse/etcd:v2.3.7-2
  environment:
    RANCHER_DEBUG: '${DEBUG}'
  entrypoint: /usr/bin/etcdhc
  command: proxy --port=:2378 --wait=60s
  links:
  - etcd
  net: container:etcd

data:
  image: busybox
  entrypoint: /bin/true
  net: none
  links:
  - etcd
  volumes:
  - /data
  labels:
    io.rancher.container.start_once: 'true'
