cassandra:
  image: llparse/cassandra:v3.7
  labels:
    io.rancher.container.pull_image: always
  environment:
    RANCHER_DEBUG: 'true'
    CASSANDRA_NAME: Rancher Cluster
  volumes:
  - /var/lib/cassandra