seed:
  image: llparse/cassandra:v3.7
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/cassandra,io.rancher.stack_service.name=$${stack_name}/seed
  environment:
    RANCHER_DEBUG: 'true'
    CASSANDRA_CLUSTER_NAME: ${CLUSTER_NAME}
    HEAP_NEWSIZE: ${HEAP_NEWSIZE}
    MAX_HEAP_SIZE: ${MAX_HEAP_SIZE}
  volumes:
  - /var/lib/cassandra
cassandra:
  image: llparse/cassandra:v3.7
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/cassandra,io.rancher.stack_service.name=$${stack_name}/seed
  environment:
    RANCHER_DEBUG: 'true'
    CASSANDRA_CLUSTER_NAME: ${CLUSTER_NAME}
    HEAP_NEWSIZE: ${HEAP_NEWSIZE}
    MAX_HEAP_SIZE: ${MAX_HEAP_SIZE}
  links:
  - seed
  volumes:
  - /var/lib/cassandra
