seed:
  image: llparse/cassandra:v3.7
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_soft: cassandra=true
  environment:
    RANCHER_DEBUG: 'true'
    CASSANDRA_CLUSTER_NAME: ${CLUSTER_NAME}
    HEAP_NEWSIZE: ${HEAP_NEWSIZE}
    MAX_HEAP_SIZE: ${MAX_HEAP_SIZE}
cassandra:
  image: llparse/cassandra:v3.7
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_soft: cassandra=true
  environment:
    RANCHER_DEBUG: 'true'
    CASSANDRA_CLUSTER_NAME: ${CLUSTER_NAME}
    HEAP_NEWSIZE: ${HEAP_NEWSIZE}
    MAX_HEAP_SIZE: ${MAX_HEAP_SIZE}
  links:
  - seed
