etcd:
  image: llparse/etcd:v3.0.3
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: data
  environment:
    ETCD_DATA_DIR: /data
    RANCHER_DEBUG: ${DEBUG}
  links:
  - data
  volumes_from:
  - data

data:
  image: busybox
  entrypoint: /bin/true
  net: none
  volumes:
  - /data
  labels:
    io.rancher.container.start_once: 'true'
