.catalog:
  name: Etcd
  version: 2.3.6-rancher2
  description: |
    Distributed highly-available key-value store
  minimum_rancher_version: v1.1.0-rc2
  questions:
    - variable: REPLICAS
      description: Number of Etcd nodes. 3, 5, or 7 are good choices
      label: Number of Nodes
      required: true
      default: 3
      type: int
etcd:
  scale_policy:
    min: 1
    max: 3
    increment: 2
  scale: ${REPLICAS}
  health_check:
    port: 2379
    request_line: '/health'
    interval: 7500
    response_timeout: 5000
    healthy_threshold: 2
    unhealthy_threshold: 4
