.catalog:
  name: Etcd
  version: 2.3.6-rancher2
  description: |
    Distributed highly-available key-value store
  minimum_rancher_version: v1.1.0-rc2
  questions:
    - variable: REPLICAS
      description: Number of Etcd nodes. 3, 5, or 7 are good choices
      label: Number of Nodes
      required: true
      default: 3
      type: int
    - variable: MIN_SCALE
      description: Minimum cluster size
      label: Min Scale
      type: int
      default: 3
      required: true
    - variable: MAX_SCALE
      description: Maximum cluster size
      label: Max Scale
      type: int
      default: 5
      required: true
    - variable: DEBUG
      description: Enable or disable verbose logging and other debugging features
      label: Debug
      type: boolean
      default: false
etcd:
  scale_policy:
    min: ${MIN_SCALE}
    max: ${MAX_SCALE}
    increment: 1
  scale: ${REPLICAS}
  health_check:
    port: 2379
    request_line: '/health'
    interval: 7500
    response_timeout: 5000
    healthy_threshold: 2
    unhealthy_threshold: 4
