scheduler:
  image: rancher/elasticsearch:latest
  environment:
    MESOS_SERVICE: ${MESOS_SERVICE}
    ZK_SERVICE: ${ZK_SERVICE}
    SCHEDULER_PORT: ${SCHEDULER_PORT}
    JAVA_OPTS: -Xms256M -Xmx256M
    NODE_COUNT: ${NODE_COUNT}
  ports:
  - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
